site_name: Synse Python Client
site_description: The official Python client for interacting with the Synse Server API.
site_author: Vapor IO

repo_url: https://github.com/vapor-ware/synse-client-python

theme: readthedocs

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: True
