#
# integration.yaml
#
# compose file for running integration tests against
# synse server with emulator plugin.
#

version: '3'
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:latest
    ports:
    - '5000:5000'
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator:5001
    links:
    - emulator

  emulator:
    container_name: emulator
    image: vaporio/emulator-plugin:latest
    expose:
    - '5001'
    command: ['--debug']
    volumes:
    - ./config:/tmp/devices
    environment:
      PLUGIN_DEVICE_CONFIG: /tmp/devices
